INSERT INTO manages (employee_name, manager_name) VALUES
('John Doe', 'Jane Smith'),
('Jane Smith',null),
('Michael Johnson',null),
('Emily Davis',null),
('Christopher Wilson', 'Daniel Lewis'),
('Daniel Anderson', 'Daniel Lewis'),
('Sarah Martinez', 'Maria Walker'),
('Jennifer Rodriguez',null),
('James Garcia', 'Michael Johnson'),
('Linda Hernandez', 'Emily Davis'),
('William Martinez', null),
('Patricia Gonzalez', 'Charles King'),
('Richard Perez', 'John Doe'),
('Susan Ramirez', 'Emily Davis'),
('Daniel Lewis',null),
('Maria Walker',null),
('Charles King', 'William Martinez'),
('Karen Wright',null),
('Jessica Taylor', 'William Martinez'),
('David Thompson', 'Jennifer Rodriguez')

